---
title: "Models"
author: "Anthony Rentsch"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 2
    collapsed: false
    smooth_scroll: false
    df_print: kable
---

```{r setup, include=FALSE, echo = FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Dependencies
library(tidyverse)

# Data
orders <- read.csv("/Users/anthonyrentsch/Desktop/UMass/Senior Year/First Semester/Advanced Data Analysis/orders.csv")
products_prior <- read.csv("/Users/anthonyrentsch/Desktop/UMass/Senior Year/First Semester/Advanced Data Analysis/order_products__prior.csv")
order_products_train <- read.csv("order_products__train.csv")
products <- read.csv("products.csv")
aisles <- read.csv("aisles.csv")
departments <- read.csv("departments.csv")
```

# Setup

```{r}
#Here, we join the orders by time with the products ordered for prior and train set orders
prior <- products_prior %>% left_join(orders, by = "order_id")
train <- order_products_train %>% left_join(orders, by = "order_id")
#Joining the prior and training sets together
orders_full <- rbind(train, prior)
```


# Predict that an individual will order the item they have ordered most

First, look at what the maximum number of times a user has ordered the same product.

```{r}
orders_full %>% group_by(user_id) %>% count(product_id) %>% summarise(max_orders = max(n)) %>% 
  ggplot() +
  geom_histogram(aes(x = max_orders), fill = "green4") +
  labs(x = "Maximum number of times a user has ordered the same product",
       title = "")
#ggsave("max_reorders.png")
```

Now use predict the next product that a user will order is product that each user has ordered most.

```{r}
max_ordered_product <- orders_full %>% group_by(user_id) %>% 
  count(product_id) 
max_ordered_product <- max_ordered_product %>% filter(n == max(n))

# predict; when a user has multiple products tied for most ordered, break at random
test <- orders %>% filter(eval_set == "test") %>% left_join(max_ordered_product, by = "user_id") 
test <- test %>% group_by(user_id) %>% sample_n(1) %>% ungroup()
  
test <- test %>% select(order_id, product_id) %>% rename(products = product_id)
write_csv(test, "max_previously_ordered.csv")
```

Kaggle F1 score: 0.1632167. 


Now retry but guessing top 2 items.

```{r}
# set up data frame to use to predict 2 or more products
max_ordered_product2 <- orders_full %>% group_by(user_id) %>% 
  count(product_id) %>% top_n(2, wt = n)
max_ordered_product2 <- max_ordered_product2 %>% select(-n)
max_ordered_product_2_ormore <- max_ordered_product2 %>% mutate(row = row_number()) %>% 
  spread(row, product_id)

test2 <- orders %>% filter(eval_set == "test") %>% left_join(max_ordered_product_2_ormore, by = "user_id")
test2 <- test2 %>% select(order_id, '1', '2')
  
test2 <- within(test2, x <- paste(test2$`1`,test2$`2`,sep=' ')) %>% rename(order_id = order_id, products = x) %>% 
  select(order_id, products)
write_csv(test2, "max_previously_ordered_2.csv")
```

Top 3 items.

```{r}
test3 <- orders %>% filter(eval_set == "test") %>% left_join(max_ordered_product_2_ormore, by = "user_id")
test3 <- test3 %>% select(order_id, '1', '2', '3')
test3$`3`[is.na(test3$`3`)] <- ""
  
test3 <- within(test3, x <- paste(test3$`1`,test3$`2`,test3$`3`,sep=' ')) %>% 
  rename(order_id = order_id, products = x) %>% 
  select(order_id, products)


write_csv(test3, "max_previously_ordered_3.csv")
```

Top 4 items.

```{r}
test4 <- orders %>% filter(eval_set == "test") %>% left_join(max_ordered_product_2_ormore, by = "user_id")
test4 <- test4 %>% select(order_id, '1', '2', '3','4')
test4$`3`[is.na(test4$`3`)] <- ""
test4$`3`[is.na(test4$`4`)] <- ""
  
test4 <- within(test4, x <- paste(test4$`1`,test4$`2`,test4$`3`,test4$`4`,sep=' ')) %>% 
  rename(order_id = order_id, products = x) %>% 
  select(order_id, products)


write_csv(test4, "max_previously_ordered_4.csv")

```
